import type {Metadata} from 'next';
import './globals.scss';
import {ReactNode} from 'react';
import '@/styles/globals.scss';
import {Poppins_Font} from '@/styles/font/font';


export const metadata: Metadata = {
	title: 'Ihor Vitrikush',
	description: 'Generated by create next app',
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: ReactNode;
}>) {
	return (
		 <html lang="en">
		 <body className={Poppins_Font.className}>{children}</body>
		 </html>
	);
}
